export const photoCards = [
  {
    address: {
      city: 'Gwenborough',
      geo: [Object],
      street: 'Kulas Light',
      suite: 'Apt. 556',
      zipcode: '92998-3874',
    },
    company: {
      bs: 'harness real-time e-markets',
      catchPhrase: 'Multi-layered client-server neural-net',
      name: 'Romaguera-Crona',
    },
    email: 'Sincere@april.biz',
    id: 1,
    name: 'Leanne Graham',
    phone: '1-770-736-8031 x56442',
    username: 'Bret',
    website: 'hildegard.org',
  },
  {
    address: {
      city: 'Wisokyburgh',
      geo: [Object],
      street: 'Victor Plains',
      suite: 'Suite 879',
      zipcode: '90566-7771',
    },
    company: {
      bs: 'synergize scalable supply-chains',
      catchPhrase: 'Proactive didactic contingency',
      name: 'Deckow-Crist',
    },
    email: 'Shanna@melissa.tv',
    id: 2,
    name: 'Ervin Howell',
    phone: '010-692-6593 x09125',
    username: 'Antonette',
    website: 'anastasia.net',
  },
  {
    address: {
      city: 'McKenziehaven',
      geo: [Object],
      street: 'Douglas Extension',
      suite: 'Suite 847',
      zipcode: '59590-4157',
    },
    company: {
      bs: 'e-enable strategic applications',
      catchPhrase: 'Face to face bifurcated interface',
      name: 'Romaguera-Jacobson',
    },
    email: 'Nathan@yesenia.net',
    id: 3,
    name: 'Clementine Bauch',
    phone: '1-463-123-4447',
    username: 'Samantha',
    website: 'ramiro.info',
  },
  {
    address: {
      city: 'South Elvis',
      geo: [Object],
      street: 'Hoeger Mall',
      suite: 'Apt. 692',
      zipcode: '53919-4257',
    },
    company: {
      bs: 'transition cutting-edge web services',
      catchPhrase: 'Multi-tiered zero tolerance productivity',
      name: 'Robel-Corkery',
    },
    email: 'Julianne.OConner@kory.org',
    id: 4,
    name: 'Patricia Lebsack',
    phone: '493-170-9623 x156',
    username: 'Karianne',
    website: 'kale.biz',
  },
  {
    address: {
      city: 'Roscoeview',
      geo: [Object],
      street: 'Skiles Walks',
      suite: 'Suite 351',
      zipcode: '33263',
    },
    company: {
      bs: 'revolutionize end-to-end systems',
      catchPhrase: 'User-centric fault-tolerant solution',
      name: 'Keebler LLC',
    },
    email: 'Lucio_Hettinger@annie.ca',
    id: 5,
    name: 'Chelsey Dietrich',
    phone: '(254)954-1289',
    username: 'Kamren',
    website: 'demarco.info',
  },
  {
    address: {
      city: 'South Christy',
      geo: [Object],
      street: 'Norberto Crossing',
      suite: 'Apt. 950',
      zipcode: '23505-1337',
    },
    company: {
      bs: 'e-enable innovative applications',
      catchPhrase: 'Synchronised bottom-line interface',
      name: 'Considine-Lockman',
    },
    email: 'Karley_Dach@jasper.info',
    id: 6,
    name: 'Mrs. Dennis Schulist',
    phone: '1-477-935-8478 x6430',
    username: 'Leopoldo_Corkery',
    website: 'ola.org',
  },
  {
    address: {
      city: 'Howemouth',
      geo: [Object],
      street: 'Rex Trail',
      suite: 'Suite 280',
      zipcode: '58804-1099',
    },
    company: {
      bs: 'generate enterprise e-tailers',
      catchPhrase: 'Configurable multimedia task-force',
      name: 'Johns Group',
    },
    email: 'Telly.Hoeger@billy.biz',
    id: 7,
    name: 'Kurtis Weissnat',
    phone: '210.067.6132',
    username: 'Elwyn.Skiles',
    website: 'elvis.io',
  },
  {
    address: {
      city: 'Aliyaview',
      geo: [Object],
      street: 'Ellsworth Summit',
      suite: 'Suite 729',
      zipcode: '45169',
    },
    company: {
      bs: 'e-enable extensible e-tailers',
      catchPhrase: 'Implemented secondary concept',
      name: 'Abernathy Group',
    },
    email: 'Sherwood@rosamond.me',
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    phone: '586.493.6943 x140',
    username: 'Maxime_Nienow',
    website: 'jacynthe.com',
  },
  {
    address: {
      city: 'Bartholomebury',
      geo: [Object],
      street: 'Dayna Park',
      suite: 'Suite 449',
      zipcode: '76495-3109',
    },
    company: {
      bs: 'aggregate real-time technologies',
      catchPhrase: 'Switchable contextually-based project',
      name: 'Yost and Sons',
    },
    email: 'Chaim_McDermott@dana.io',
    id: 9,
    name: 'Glenna Reichert',
    phone: '(775)976-6794 x41206',
    username: 'Delphine',
    website: 'conrad.com',
  },
  {
    address: {
      city: 'Lebsackbury',
      geo: [Object],
      street: 'Kattie Turnpike',
      suite: 'Suite 198',
      zipcode: '31428-2261',
    },
    company: {
      bs: 'target end-to-end models',
      catchPhrase: 'Centralized empowering task-force',
      name: 'Hoeger LLC',
    },
    email: 'Rey.Padberg@karina.biz',
    id: 10,
    name: 'Clementina DuBuque',
    phone: '024-648-3804',
    username: 'Moriah.Stanton',
    website: 'ambrose.net',
  },
];

const b = {
  results: [
    {
      user: {
        gender: 'male',
        name: {title: 'mr', first: 'adam', last: 'richards'},
        location: {
          street: '1661 eighth st',
          city: 'duncanville',
          state: 'wisconsin',
          zip: '36170',
        },
        email: 'adam.richards38@example.com',
        username: 'smalldog71',
        password: '666666',
        salt: 'Q6MKxOg3',
        md5: 'cf720272fb2d1848e72b4cf34025666b',
        sha1: '74eee06e2e7870c3e1ae0b826db581153c923b5a',
        sha256:
          'd6da2f02e296bf9c4b7f646dd97e7e644091d28e6c932b91f8d8dae239744e64',
        registered: '1439052132',
        dob: '304548005',
        phone: '(192)-852-7257',
        cell: '(121)-225-4429',
        SSN: '213-74-5527',
        picture: 'http://api.randomuser.me/portraits/men/92.jpg',
      },
      seed: 'fcdbae3922a01dfd',
      version: '0.4',
    },
  ],
};

let c = {
  SSN: '469-71-2154',
  cell: '(226)-547-9957',
  dob: '146296153',
  email: 'clinton.burton81@example.com',
  gender: 'male',
  location: {
    city: 'san diego',
    state: 'mississippi',
    street: '3945 lakeview st',
    zip: '74615',
  },
  md5: '569e0bc7ff2b785e15ff72cbd2279b86',
  name: {first: 'clinton', last: 'burton', title: 'mr'},
  password: 'knockers',
  phone: '(152)-263-1897',
  picture: 'http://api.randomuser.me/portraits/men/44.jpg',
  registered: '1372723826',
  salt: 'jvN9UMxt',
  sha1: '6f2ec1070a9c8092b7a937359880df6c9b9bc142',
  sha256: 'eafdeca2b9a027c00af7bc2fb739174845407f31cbec19f773c656fec6e57c7a',
  username: 'heavycat641',
};
